locale: "ja"
backend:
  name: github
  repo: nam3/blog
  branch: main
media_folder: "/static/images/from-cms"
public_folder: "/images/from-cms"
collections:
  - name: blog
    label: "ブログ"
    folder: "src/contents"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{path-alias}}"
    fields:
      - {
        label: layout,
        name: layout,
        widget: hidden,
        default: blog,
      }
      - {
        label: "タイトル",
        name: title,
        widget: string,
      }
      - {
        label: "URL: https://blog.com/{ここに入るURLです} (英数小文字とハイフンのみ使用可能)",
        name: path-alias,
        pattern: ['^([a-z0-9-]{4,})$', "4文字以上の英数小文字とハイフンを入力してください"],
        widget: string,
      }
      - {
        label: "最終更新日",
        name: published-date,
        widget: datetime,
      }
      - {
        label: "サムネイル画像",
        name: thumbnail,
        widget: image,
        default: "/images/from-cms/mr-saturn.png",
      }
      - {
        label: "本文",
        name: body,
        widget: markdown,
      }
